blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Ask a question in the forum
    url: https://github.com/microsoft/generative-pipelines/discussions/categories/general
    about: Start a Q&A discussion in the repository
  - name: ï¸ğŸ¨Feature request
    url: https://github.com/microsoft/generative-pipelines/discussions/categories/general
    about: Describe your scenario and suggest a feature
  - name: ğŸ¤ Show & Tell
    url: https://github.com/microsoft/generative-pipelines/discussions/categories/show-and-tell
    about: Show off something you've made
